name       : utopia-documents
version    : 3.1
release    : 4
source     :
    - http://utopiadocs.com/files/utopia-documents-3.1.0.tgz : e6db50a16d2ae53ce051217e6941c5796bf5b9d517b0623ab6ff0b617b04f365
license    : GPL-3.0
component  : office.viewers
summary    : Utopia Documents is a free PDF reader that connects the static content
    of scientific articles to the dynamic world of online content.
description: |
    Utopia Documents is a free PDF reader that connects the static content of scientific articles to the dynamic world of online content.
libsplit   : no
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - libboost-devel
    - pytest-runner
    - python-setuptools
    - swig
rundeps    :
    - python-lxml
    - python-pillow
setup      : |
    %apply_patches
build      : |
    # Generate dependencies/dependencies.cmake which is required for cmake in main directory
    pushd dependencies
    %cmake -CCMakeConfig/configurations/common.txt -CCMakeConfig/configurations/Linux.txt .
    %make # Does nothing
    popd

    # Build utopia-documents
    mkdir -p build
    pushd build
    %cmake -C$workdir/CMakeConfig/configurations/common.txt -C$workdir/CMakeConfig/configurations/Linux.txt ..
    %make
    popd
install    : |
    %make_install -C build
